### ISSUE TITLE
tron_grid.png file missing

### ISSUE THREAD

**Issue by SatishMavani** [markdaws/arkit-by-example#4]
Hi Mark,

tron_grid.png file is missing i downloaded code of branch "part2"

**Comment by OxyFlax** [comment]
Do you have the file in your project folder and in your Xcode project? It's visible in the part2 branch so you should have it.
If it's the case, maybe the box is unchecked in the Xcode project. Click on the image and check the box "arkit-by-example" inside "Target Membership" in the file inspector ;)

**Comment by SatishMavani** [comment]
No file was not there in folder to, it was showing as deleted in xcode, then i copied file from master repo folder and pasted in my part2 code, working now.
Thanks again.

**Comment by OxyFlax** [comment]
Ok, can you close the issue please? :)
