### ISSUE TITLE
White screen?

### ISSUE THREAD

**Issue by diegotrigo** [markdaws/arkit-by-example#8]
Hi there,
I've installed on my iOS11, however I can't see the camera. Although the app loads correctly, it show only a white screen with all the controls (menu, toggle etc..).
Any idea?

**Comment by markdaws** [comment]
Hi - what type of device are you using?

**Comment by diegotrigo** [comment]
iPhone MG472TA (I think it's iPhone 6?).
Isn't supported?

D

**Comment by markdaws** [comment]
Unfortunately not. ARKit needs an A9 chip and above. Looks like the iPhone6 is an A8 chip.
